eureka:
  client:
    register-with-eureka: false

server:
  port: 8222

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
        - id: business
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/business/**

application:
  security:
    jwt:
      secret-key: 5d9bcee44a9f0549cf53d86206bf8d1e98c675ce843bab16685e9d1056e64633
      expiration: 86400000 # a day


